spring:
  datasource:
    url: jdbc:mysql://localhost:3306/railwayparceltransport
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

      spring:
        security:
          user:
            name: admin            # Default username for basic security setup
            password: admin123      # Default password
            roles: ADMIN            # Default role
          enable-default-security: false  # Disable default security configuration (optional)

          jwt:
            secret: qL0xkzE+m/7yOvBt2nD4Lb5RWnl1FslFUMGdE+KQW68=
